# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 01:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(default='', max_length=500)),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=3)),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
                ('state', models.IntegerField(choices=[(1, 'QLD'), (2, 'NSW'), (3, 'ACT'), (4, 'VIC'), (5, 'SA'), (6, 'WA'), (7, 'NT'), (8, 'TAS')], default=1)),
                ('postcode', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)])),
                ('userType', models.IntegerField(choices=[(1, 'student'), (2, 'businessman'), (3, 'tourist')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
