# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'No')], default=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Select one'), (2, 'student'), (3, 'businessman'), (4, 'tourist')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'No')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Select one'), (2, 'student'), (3, 'businessman'), (4, 'tourist')]),
        ),
    ]
