# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171023_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dob',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='postcode',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='userType',
            field=models.CharField(default='', max_length=500),
        ),
    ]
